# The ExternalSecret specifies what to fetch, 
# This resource is namespaced.
# In addition, the external secret uses the configuration under secretStoreRef to create/manage a secret with the secret key and value.

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: external-secrets
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: test-secret
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: app-postgres-secret
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: app-postgres-secret
        property: password
