global:
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  affinity: {}
  compatibility:
    openshift:
      adaptSecurityContext: auto

replicaCount: 1

bitwarden-sdk-server:
  enabled: false
  namespaceOverride: ""

# -- Specifies the amount of historic ReplicaSets k8s should keep (see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy)
revisionHistoryLimit: 10

image:
  repository: oci.external-secrets.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  # -- The image tag to use. The default is the chart appVersion.
  tag: ""
  flavour: ""

# -- If set, install and upgrade CRDs through helm chart.
installCRDs: true

crds:
  # -- If true, create CRDs for Cluster External Secret.
  createClusterExternalSecret: true
  # -- If true, create CRDs for Cluster Secret Store.
  createClusterSecretStore: true
  # -- If true, create CRDs for Cluster Generator.
  createClusterGenerator: true
  # -- If true, create CRDs for Cluster Push Secret.
  createClusterPushSecret: true
  # -- If true, create CRDs for Push Secret.
  createPushSecret: true
  annotations: {}
  conversion:
    # -- Conversion is disabled by default as we stopped supporting v1alpha1.
    enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

commonLabels: {}

leaderElect: false

controllerClass: ""

extendedMetricLabels: false

scopedNamespace: ""

scopedRBAC: false

openshiftFinalizers: true

systemAuthDelegator: false

processClusterExternalSecret: true

processClusterPushSecret: true

# -- if true, the operator will process cluster store. Else, it will ignore them.
processClusterStore: true

# -- if true, the operator will process cluster generator. Else, it will ignore them.
processClusterGenerator: true

# -- if true, the operator will process push secret. Else, it will ignore them.
processPushSecret: true

# -- Specifies whether an external secret operator deployment be created.
createOperator: true

# -- if true, HTTP2 will be enabled for the services created by all controllers, curently metrics and webhook.
enableHTTP2: false

# -- Specifies the number of concurrent ExternalSecret Reconciles external-secret executes at
# a time.
concurrent: 1
# -- Specifies Log Params to the External Secrets Operator
log:
  level: info
  timeEncoding: epoch
service:
  # -- Set the ip family policy to configure dual-stack see [Configure dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services)
  ipFamilyPolicy: ""
  # -- Sets the families that should be supported and the order in which they should be applied to ClusterIP as well. Can be IPv4 and/or IPv6.
  ipFamilies: []

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- Automounts the service account token in all containers of the pod
  automount: true
  # -- Annotations to add to the service account.
  annotations: {}
  # -- Extra Labels to add to the service account.
  extraLabels: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

rbac:
  # -- Specifies whether role and rolebinding resources should be created.
  create: true

  servicebindings:
    # -- Specifies whether a clusterrole to give servicebindings read access should be created.
    create: true

  # -- Specifies whether permissions are aggregated to the view ClusterRole
  aggregateToView: true

  # -- Specifies whether permissions are aggregated to the edit ClusterRole
  aggregateToEdit: true

## -- Extra environment variables to add to container.
extraEnv: []

## -- Map of extra arguments to pass to container.
extraArgs: {}

## -- Extra volumes to pass to pod.
extraVolumes: []

## -- Extra Kubernetes objects to deploy with the helm chart
extraObjects: []

## -- Extra volumes to mount to the container.
extraVolumeMounts: []

## -- Extra init containers to add to the pod.
extraInitContainers: []

## -- Extra containers to add to the pod.
extraContainers: []

# -- Annotations to add to Deployment
deploymentAnnotations: {}

 # -- Set deployment strategy
strategy: {}

# -- Annotations to add to Pod
podAnnotations: {}

podLabels: {}

podSecurityContext:
  enabled: true
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  enabled: true
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

resources: {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi

serviceMonitor:
  # -- Specifies whether to create a ServiceMonitor resource for collecting Prometheus metrics
  enabled: false

  # -- How should we react to missing CRD "`monitoring.coreos.com/v1/ServiceMonitor`"
  #
  # Possible values:
  # - `skipIfMissing`: Only render ServiceMonitor resources if CRD is present, skip if missing.
  # - `failIfMissing`: Fail Helm install if CRD is not present.
  # - `alwaysRender` : Always render ServiceMonitor resources, do not check for CRD.

  # @schema
  # enum:
  # - skipIfMissing
  # - failIfMissing
  # - alwaysRender
  # @schema
  renderMode: skipIfMissing   # @schema enum: [skipIfMissing, failIfMissing, alwaysRender]

  # -- namespace where you want to install ServiceMonitors
  namespace: ""

  # -- Additional labels
  additionalLabels: {}

  # --  Interval to scrape metrics
  interval: 30s

  # -- Timeout if metrics can't be retrieved in given time interval
  scrapeTimeout: 25s

  # -- Let prometheus add an exported_ prefix to conflicting labels
  honorLabels: false

  # -- Metric relabel configs to apply to samples before ingestion. [Metric Relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs)
  metricRelabelings: []
  # - action: replace
  #   regex: (.*)
  #   replacement: $1
  #   sourceLabels:
  #   - exported_namespace
  #   targetLabel: namespace

  # -- Relabel configs to apply to samples before ingestion. [Relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config)
  relabelings: []
  # - sourceLabels: [__meta_kubernetes_pod_node_name]
  #   separator: ;
  #   regex: ^(.*)$
  #   targetLabel: nodename
  #   replacement: $1
  #   action: replace

metrics:

  listen:
    port: 8080
    secure:
      enabled: false
      # -- if those are not set or invalid, self-signed certs will be generated
      # -- TLS cert directory path
      certDir: /etc/tls
      # -- TLS cert file path
      certFile: /etc/tls/tls.crt
      # -- TLS key file path
      keyFile: /etc/tls/tls.key

  service:
    # -- Enable if you use another monitoring tool than Prometheus to scrape the metrics
    enabled: false

    # -- Metrics service port to scrape
    port: 8080

    # -- Additional service annotations
    annotations: {}

grafanaDashboard:
  # -- If true creates a Grafana dashboard.
  enabled: false

  # -- Label that ConfigMaps should have to be loaded as dashboards.
  sidecarLabel: "grafana_dashboard"

  # -- Label value that ConfigMaps should have to be loaded as dashboards.
  sidecarLabelValue: "1"

  # -- Annotations that ConfigMaps can have to get configured in Grafana,
  # See: sidecar.dashboards.folderAnnotation for specifying the dashboard folder.
  # https://github.com/grafana/helm-charts/tree/main/charts/grafana
  annotations: {}

  # -- Extra labels to add to the Grafana dashboard ConfigMap.
  extraLabels: {}

livenessProbe:
  # -- Enabled determines if the liveness probe should be used or not. By default it's disabled.
  enabled: false
  # -- The body of the liveness probe settings.
  spec:
    # -- Address for liveness probe.
    address: ""
    # -- Specify the maximum amount of time to wait for a probe to respond before considering it fails.
    timeoutSeconds: 5
    # -- Number of consecutive probe failures that should occur before considering the probe as failed.
    failureThreshold: 5
    # -- Period in seconds for K8s to start performing probes.
    periodSeconds: 10
    # -- Number of successful probes to mark probe successful.
    successThreshold: 1
    # -- Delay in seconds for the container to start before performing the initial probe.
    initialDelaySeconds: 10
    # -- Handler for liveness probe.
    httpGet:
      # -- Set this value to 8082 to active liveness probes.
      # @schema type: [string, integer]
      port: 8082
      # -- Path for liveness probe.
      path: /healthz

nodeSelector: {}

tolerations: []

topologySpreadConstraints: []

affinity: {}

# -- Pod priority class name.
priorityClassName: ""

# -- Pod disruption budget - for more details see https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
podDisruptionBudget:
  enabled: false
  minAvailable: 1    # @schema type:[integer, string]
  nameOverride: ""
  # maxUnavailable: "50%"

# -- Run the controller on the host network
hostNetwork: false

webhook:
  # -- Annotations to place on validating webhook configuration.
  annotations: {}
  # -- Specifies whether a webhook deployment be created. If set to false, crds.conversion.enabled should also be set to false otherwise the kubeapi will be hammered because the conversion is looking for a webhook endpoint.
  create: true
  # -- Specifies the time to check if the cert is valid
  certCheckInterval: "5m"
  # -- Specifies the lookaheadInterval for certificate validity
  lookaheadInterval: ""
  replicaCount: 1
  # -- Specifies Log Params to the Webhook
  log:
    level: info
    timeEncoding: epoch
  # -- Specifies the amount of historic ReplicaSets k8s should keep (see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy)
  revisionHistoryLimit: 10

  certDir: /tmp/certs
  # -- Specifies whether validating webhooks should be created with failurePolicy: Fail or Ignore
  failurePolicy: Fail
  # -- Specifies if webhook pod should use hostNetwork or not.
  hostNetwork: false
  image:
    repository: oci.external-secrets.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    # -- The image tag to use. The default is the chart appVersion.
    tag: ""
    # -- The flavour of tag you want to use
    flavour: ""
  imagePullSecrets: []
  # -- The port the webhook will listen to
  port: 10250
  serviceAccount:
    # -- Specifies whether a service account should be created.
    create: true
    # -- Automounts the service account token in all containers of the pod
    automount: true
    # -- Annotations to add to the service account.
    annotations: {}
    # -- Extra Labels to add to the service account.
    extraLabels: {}
    # -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template.
    name: ""
  nodeSelector: {}

  certManager:
    # -- Enabling cert-manager support will disable the built in secret and
    # switch to using cert-manager (installed separately) to automatically issue
    # and renew the webhook certificate. This chart does not install
    # cert-manager for you, See https://cert-manager.io/docs/
    enabled: false
    # -- Automatically add the cert-manager.io/inject-ca-from annotation to the
    # webhooks and CRDs. As long as you have the cert-manager CA Injector
    # enabled, this will automatically setup your webhook's CA to the one used
    # by cert-manager. See https://cert-manager.io/docs/concepts/ca-injector
    addInjectorAnnotations: true
    cert:
      # -- Create a certificate resource within this chart. See
      # https://cert-manager.io/docs/usage/certificate/
      create: true
      # -- For the Certificate created by this chart, setup the issuer. See
      # https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.IssuerSpec
      issuerRef:
        group: cert-manager.io
        kind: "Issuer"
        name: "my-issuer"
      # -- Set the requested duration (i.e. lifetime) of the Certificate. See
      # https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
      # One year by default.
      duration: "8760h"
      # -- Set the revisionHistoryLimit on the Certificate. See
      # https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
      # Defaults to 0 (ignored).
      revisionHistoryLimit: 0
      # -- How long before the currently issued certificateâ€™s expiry
      # cert-manager should renew the certificate. See
      # https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
      # Note that renewBefore should be greater than .webhook.lookaheadInterval
      # since the webhook will check this far in advance that the certificate is
      # valid.
      renewBefore: ""
      # -- Add extra annotations to the Certificate resource.
      annotations: {}

  tolerations: []

  topologySpreadConstraints: []

  affinity: {}
  strategy: {}
  priorityClassName: ""

  # -- Pod disruption budget - for more details see https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  podDisruptionBudget:
    enabled: false
    minAvailable: 1    # @schema type:[integer, string]
    nameOverride: ""
    # maxUnavailable: "50%"

  metrics:

    listen:
      port: 8080

    service:
      enabled: false
      port: 8080
      annotations: {}


  readinessProbe:
    address: ""
    port: 8081

  extraEnv: []
  
  extraArgs: {}

  extraInitContainers: []

  extraVolumes: []

  extraVolumeMounts: []

  secretAnnotations: {}

  deploymentAnnotations: {}

  podAnnotations: {}

  podLabels: {}

  podSecurityContext:
    enabled: true
      # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  resources: {}
      # requests:
      #   cpu: 10m
      #   memory: 32Mi

  service:
    enabled: true
    annotations: {}
    labels: {}
    type: ClusterIP
    loadBalancerIP: ""

certController:
  # -- Specifies whether a certificate controller deployment be created.
  create: true
  requeueInterval: "5m"
  replicaCount: 1
  log:
    level: info
    timeEncoding: epoch
  revisionHistoryLimit: 10

  image:
    repository: oci.external-secrets.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    tag: ""
    flavour: ""
  imagePullSecrets: []
  rbac:
    create: true
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    extraLabels: {}
    name: ""
  nodeSelector: {}

  tolerations: []

  topologySpreadConstraints: []

  affinity: {}

  strategy: {}

  hostNetwork: false
  
  priorityClassName: ""

  # -- Pod disruption budget - for more details see https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  podDisruptionBudget:
    enabled: false
    minAvailable: 1    # @schema type:[integer, string]
    nameOverride: ""
    # maxUnavailable: "50%"

  metrics:

    listen:
      port: 8080

    service:
      enabled: false
      port: 8080
      annotations: {}

  readinessProbe:
    address: ""
    port: 8081

  startupProbe:
    enabled: false
    useReadinessProbePort: true
    port: ""

  extraEnv: []

  extraArgs: {}

  extraInitContainers: []

  extraVolumes: []
  
  extraVolumeMounts: []

  deploymentAnnotations: {}

  podAnnotations: {}

  podLabels: {}

  podSecurityContext:
    enabled: true
      # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  resources: {}
      # requests:
      #   cpu: 10m
      #   memory: 32Mi

dnsPolicy: ClusterFirst

dnsConfig: {}

podSpecExtra: {}
